spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:D:/WebGIS/Projects/water-level-data-monitoring/resource/water_level.db
      driver-class-name: org.sqlite.JDBC

pythondir:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/
python:
  python
basedir:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/data/
data-path:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/utc+8_data/
singleFileDir:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/all/
waterleveldb:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/water_level.db
stationnamejson:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/station_name.json


#长江下游网站
waterlevellog:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/yangtze_downstream_log.txt
yangtzeDownstreamStationJson:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/yangtze_downstream_station.json

#浙江水情网
zhejianglog:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/zhejiang_log.txt
zhejiangjson:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/zhejiang_station.json

#安徽水情网
anhuilog:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/anhui_log.txt
anhuijson:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/nodescript/station.json
nodescriptpath:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/nodescript/

#江苏水情网
jiangsulog:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/jiangsu_log.txt
jiangsujson:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/jiangsu_station.json
pngpath:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/png/

#湖北水情网
hubeiLog:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/hubei_log.txt
hubeiJson:
  D:/WebGIS/Projects/water-level-data-monitoring/resource/hubei_station.json




#水位预报模型地址
predictionPath: D:/WebGIS/Projects/water-level-data-monitoring/resource/prediction/




